/*let click=document.getElementById("clickBtn")
let outparagraph=document.getElementById( " clickOutput")
click.addEventListener("click" , function (){ click.style.background="red"
})
let dbl=document.getElementById( " dblClickBtn")
dbl.addEventListener("dbl" , () => dbl. textContent(" wow "))
dbl.addEventListener( " dbl " , funactoin( ){
    outparagraph.textContent
} 
add
)*/
//let mouse=document.getElementById("hover-box")
//mouse.addEventListener("mouseOver",funactoin() { mouse.style.background=" blue"

let hover=document.getElementById("hoverBox")
hover.addEventListener("mouseover", ()=> hover.style.background="green")
hover.addEventListener("mouseout", ()=> hover.style.background="red")

let textfocus=document.getElementById("focusInput")
textfocus.addEventListener("focus",()=>{
     
} )
let selectvalue=document.getElementById("selectInput")
let output=document.getElementById("inputOutput")
selectvalue.addEventListener("change" , (event)=> {
    output.innerhtml=event.target.value
})










 




